### PR TITLE
feat: add support for maintaining `package.json` indentation level when sorting

### LINKED ISSUE #33: Maintain indenting level
NPM respects the indentation level of `package.json`; if you use 4 spaces for indenting, npm will maintain that, rather than reverting it back to 2 spaces everytime it makes a change to the `package.json`.

Currently it seems `sort-package-json` doesn't respect indentation level, and just instead reverts the `package.json` to 2 spaces.

### PR DESCRIPTION
**Pull request by G-Rath**
This is the same way `npm` does it.

I had to alter a test that was actually testing specifically that the indentation had been formatted, so now it's testing that the indentation hasn't changed.

fixes #33

### CODE REVIEW

**Comment by G-Rath** [comment]
This also generated a `package-lock.json`, that I've not committed since one doesn't already exist, but I would advise adding one. 

Let me know if you'd like me to add it as part of this PR.

**Comment by keithamus** [comment]
This looks awesome @G-Rath! Please do go ahead and add the package-lock.json, also if you could add one or two tests just to test the indenting behavior, so we know if it were to fail, that'd be awesome!

**Comment by G-Rath** [comment]
@keithamus done and done 👍

**Comment by keithamus** [comment]
Wonderful work @G-Rath! Should be released very soon 😉

**Pull request merged**
