### PR TITLE
feat: sort `eslintConfig` deeper

### PR DESCRIPTION
**Pull request by fisker**
the testes become hard to write, should we have a test lib that supports snap testing?

### CODE REVIEW

**Comment by keithamus** [comment]
We can give snapshot testing a go if you would like. I generally dislike it because it is usually treated as opaque and so developers just commit the new snapshots whenever they break, meaning they become useless. But I suppose we can have the discipline to check for this with each PR.

**Comment by fisker** [comment]
`ava` `jest` or any other lib you prefer?

**Comment by keithamus** [comment]
I'll leave this decision to you! Whatever you prefer!

**Pull request merged**
