### PR TITLE
fix: Tests are unreliable in Windows

### LINKED ISSUE #71: Tests are unreliable in Windows
Windows git users often set `core.autocrlf` to true, so the package.json file may have CRLF line endings. The tests expect this file to have LF line endings.

### PR DESCRIPTION
**Pull request by tylerbutler**
Fixes #71.

### CODE REVIEW

**Comment by keithamus** [comment]
Thanks for this PR @tylerbutler!

Is this necessary? Is it simply the tests that fail or does `npx sort-package-json` break npm/node?

**Comment by tylerbutler** [comment]
@keithamus Thanks for the merge! This fix wasn't strictly necessary, but since there are pre-commit hooks that run the tests, I needed to fix them anyway to unblock fixing #73. :) This should make it easier for Windows users to contribute in the future too.

**Comment by keithamus** [comment]
Many thanks! Hope to see more contributions from you and I’m sure the future windows contributors will thank you! Happy coding!

**Pull request merged**
