### PR TITLE
feat: add remarkConfig field

### PR DESCRIPTION
**Pull request by jeddy3**
Adds [remark]() amongst ESLint and stylelint.

It is a popular package with [8M/monthly downloads](https://www.npmjs.com/package/remark). We use it to [lint the Markdown files](https://github.com/stylelint/stylelint/blob/0a8efea5e6e3bf8f1fc61492296669d1160ec4fd/package.json#L251-L261) across the stylelint repositories.

It [uses the `remarkConfig` property](https://github.com/remarkjs/remark-lint/blob/master/readme.md#cli).

### CODE REVIEW

**Comment by fisker** [comment]
Should also tested in https://github.com/keithamus/sort-package-json/blob/master/tests/fields.js

**Comment by jeddy3** [comment]
Thanks for the heads-up. I've added it to the `sortObjectAlphabetically` test in `fields.js`.

**Comment by jeddy3** [comment]
It looks like the CI didn't trigger. Perhaps because the pull request comes from a fork?

**Comment by keithamus** [comment]
Looks like travis-ci is dead :( we should move to GitHub Actions

**Comment by fisker** [comment]
travis-ci is dead?

**Comment by keithamus** [comment]
It looks like it's only running half the time

**Pull request merged**
