### PR TITLE
feat: add support for react-native key

### PR DESCRIPTION
**Pull request by angeloashmore**
Adds support for the `react-native` key for packages providing a [React Native](https://reactnative.dev/)-specific entry.

See the following line for React Native's package resolution strategy (via Metro): https://github.com/facebook/metro/blob/347b1d7ed87995d7951aaa9fd597c04b06013dac/packages/metro/src/DeltaBundler/__tests__/resolver-test.js#L73

### CODE REVIEW

**Review by keithamus — APPROVED** [review]

**Comment by angeloashmore** [comment]
@keithamus Thanks for taking a look at this. Yes, I will update the snapshots, but I'm having trouble installing the dependencies locally.

I get this ENOTFOUND error when running `npm i`:

```
npm ERR! code ENOTFOUND
npm ERR! syscall getaddrinfo
npm ERR! errno ENOTFOUND
npm ERR! network request to https://nexus.core.cvent.org/nexus/repository/npm-public/typescript/-/typescript-4.0.5.tgz failed, reason: getaddrinfo ENOTFOUND nexus.core.cvent.org
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
```

Indeed, that address does not point to anywhere on my network.

Is there something I'm supposed to set up?

**Comment by keithamus** [comment]
Looks like a PR leaked custom proxies into the package-lock from https://github.com/keithamus/sort-package-json/pull/206.

If you remove the package-lock.json and re-run `npm i` it should fix things.

**Comment by angeloashmore** [comment]
Thanks, I wasn't sure if those URLs were intentional. I've updated `package-lock.json` and snapshots.

I believe it should be good to go now.

**Review by keithamus — APPROVED** [review]
Thanks for your patience and perseverance here!

**Comment by angeloashmore** [comment]
No problem! 🙂 Thanks for sticking with me, too!

**Pull request merged**
