### PR TITLE
Revert "refactor!: migrate to esm and update dependencies (#256)"

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
This reverts commit 3e4ff74ea4126a417c7e5aff6d6d9d8a4f7c8b8a.

#256 should have ben a breaking/major release.

CC/ @fisker @keithamus

### CODE REVIEW

**Review by keithamus — APPROVED** [review]
Quite right. This one slipped through. Thanks!

**Comment by ph-fritsche** [comment]
I just happened to have this contribution in my Feed. Have a look at [ph-fritsche/action-release](https://github.com/ph-fritsche/action-release).
It's a GitHub Action wrapper for `semantic-release` and it [defaults to Conventional Commits](https://github.com/ph-fritsche/action-release#defaults), i.e. `refactor!:` triggers a major release.

**Comment by MichaelDeBoey** [comment]
@ph-fritsche What's the difference with [`cycjimmy/semantic-release-action`](https://github.com/cycjimmy/semantic-release-action)?

**Comment by ph-fritsche** [comment]
First of all it's written in Typescript, is unit-tested and dogfeeds itself. I initially wanted to write a PR for cycjimmy's code, but wasn't confident to implement new features without tests or types so I started from scratch.

* There is a [default config](https://github.com/ph-fritsche/action-release/blob/master/src/defaultConfig.ts) that sets the `preset` to `conventionalcommits`, adds `main` to the release branches and omits the `npm` and `github` plugin if you omit the respective token.

* It installs the appropriate `conventional-changelog` package and any plugins you list in an inline or shared config.

* It adds and updates moving tags, i.e. for a `v1.2.3` it also moves `v1.2` and - if there isn't already a `v1.3` - `v1` to that commit, or for a `v1.2.3-alpha.4` it moves the `v1.2.3-alpha` tag.

**Comment by fisker** [comment]
Should we revert it back? The original PR is fine, only  because the release bot not work as expected, we should revert this one and make sure we release v2.

**Pull request merged**
