### PR TITLE
refactor!: migrate to esm and update dependencies

### LINKED ISSUE #227: globby v12
`globby` v12 got released recently: 
https://github.com/sindresorhus/globby/releases/tag/v12.0.0

It’s used in [`cli.js`](https://github.com/keithamus/sort-package-json/blob/9b76ec173288da0844b975191955f9ee661c50ec/cli.js#L3) and is therefore [listed as a project dependency in `package.json`](https://github.com/keithamus/sort-package-json/blob/0f1c9565cf58e6a2dd0b462759f19068422f4f5e/package.json#L77).

Downstream projects with `globby` v11 or v12 end up with duplicate package instance, which would be nice to fix. As of today, [`globby` v10](https://www.npmjs.com/package/globby/v/10.0.0) is two years old (2019-06-29).

To upgrade `globby` to v12, it will be necessary to replace `require` with `import`, which will make Node 12.20 the minimum supported version for `sort-package-json`. Given this breaking change, maybe there is a window of opportunities to make other updates too?

Happy to help if needed!

### LINKED ISSUE #247: Please update `globby@10.0.0` to at least 11.0.0
### Brief
sort-package-json@1.54.0 problem located

using globby@10.0.0
https://github.com/keithamus/sort-package-json/blob/v1.54.0/package.json#L77

### History
globby@10.0.0 has problem "Including @types/glob in dependencies breaks typescript implementations"

https://github.com/sindresorhus/globby/issues/129

Fixed in "Get rid of glob dependency"
https://github.com/sindresorhus/globby/pull/135

> Drop glob and @types/glob dependencies

https://github.com/sindresorhus/globby/commits/v11.0.0

### Comparison: package.json
globby@10.0.0
https://github.com/sindresorhus/globby/blob/v10.0.2/package.json#L59

globby@11.0.0
https://github.com/sindresorhus/globby/blob/v11.0.0/package.json#L59

### Related
https://github.com/microsoft/TypeScript/issues/48341

### LINKED ISSUE #254: Migrate to ES Module?

### PR DESCRIPTION
**Pull request by fisker**
Fixes #254
Fixes #247
Fixes #227
Closes #255

[BREAKING]: Require Node.js 12

### CODE REVIEW

**Review by keithamus — DISMISSED** [review]
If we merge will semantic release cut a release? Should we batch this with the other breaking changes?

**Comment by fisker** [comment]
I don't know. Let me update other deps in this one then.

**Comment by fisker** [comment]
I think we need to update `index.d.ts`? I'm not familiar with types, can you fix it?

**Review by keithamus — DISMISSED** [review]

**Review by keithamus — APPROVED** [review]

**Comment by keithamus** [comment]
Looks like the refactor didn't trigger a release, but I imagine the next one will be breaking.

**Comment by fisker** [comment]
Looks like the breaking change should trgger by the commit message **footer** https://semantic-release.gitbook.io/semantic-release/#how-does-it-work

**Comment by pSnehanshu** [comment]
This should have been a major version bump.

**Comment by MichaelDeBoey** [comment]
@fisker @keithamus This should have been in a breaking/major release.

I created #259 to revert this PR.
We could add it again & make sure it's a breaking/major release afterwards, but this is making sure the package isn't breaking dependents anymore.

**Pull request merged**
