### PR TITLE
feat: add export default

### PR DESCRIPTION
**Pull request by bluelovers**
make sure import default can work

### CODE REVIEW

**Comment by fisker** [comment]
Can you explain why we need this?

**Comment by bluelovers** [comment]
```ts
import sortPackageJson from 'sort-package-json'
```

for use typescript when `esModuleInterop` not `true`

**Comment by fisker** [comment]
I  thought people use 

```ts
import {sortPackageJson} from 'sort-package-json'
```

or

```ts
import sortPackageJson = require('sort-package-json')
```

**Comment by bluelovers** [comment]
that 2 syntax not a good style in this case

**Pull request closed without merging**
