### PR TITLE
feat: prepend custom order to default sort order

### PR DESCRIPTION
**Pull request by fisker**
Make custom sortOrder prepend to defaultSortOrder, instead of override it, so user only need send keys that must on top, the rest known fields still sort by defaultOrder.
Should be much easier to use.

### CODE REVIEW

**Comment by fisker** [comment]
forgot custom order could be function, should support?

**Comment by keithamus** [comment]
We should support custom sort order being a function too.

**Comment by fisker** [comment]
@keithamus I can add type check here, but are you ok with prepending custom sort order array to default array?

**Comment by keithamus** [comment]
I think #102 subsumed this. Do you want to rebase for the test case at least?

**Comment by keithamus** [comment]
I like how small this PR ended up being

**Pull request merged**
